version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    # environment:
    #   DATABASE_URL: postgresql://michael:passwordpassword@db:5432/dreamvacations

  db:
    image: postgres:13
    restart: always
    env_file:
      - ./db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname dreamvacations --username michael"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
